inventory/urls.py
from django.urls import path
import inventory.views as views

app_name = 'inventory'
urlpatterns=[
    path('', views.inventory_report, name='inventory'),
    path('upload_inventory', views.upload_inventory, name='upload_inventory'),
    path('inventory_report', views.inventory_report, name='inventory_report'),
    path('download/<filename>', views.download, name='download')
    ]

members/urls.py
from django.urls import path
import members.views as views

app_name = 'members'
urlpatterns=[
    path('', views.members_report, name='members'),
    path('members_report', views.members_report, name='members_report'),
    path('download/<filename>', views.download, name='download')
    ]

sales_report/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url = 'members/', permanent = True)),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('members/', include('members.urls', namespace='members')),
    path('smt_report/', include('smt_report.urls', namespace='smt_report')),
]




urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>報表 {% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  {% load static %}
  <link rel="Shortcut Icon" type="image/x-icon" href="{% static 'img/logo.png' %}">
  <!-- font awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <!-- bootstrap css -->
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% block css %} {% endblock css %}
</head>
<body style="background-color: #f5f5f5;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">系統報表</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">銷售報表</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'members:members_report' %}">會員報表</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory:inventory_report' %}">庫存報表</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                資料上傳
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'inventory:upload_inventory' %}">庫存資料上傳</a>
                <a class="dropdown-item" href="#">銷售資料上傳</a>
              </div>
            </li>
	      <li class="nav-item">
		<a class="nav-link" href="/admin">管理控制台</a>
              </li>
            <li class="nav-item dropdown">

          </ul>
        </div>
      </nav>
    {% block body %}
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <!-- jquery ui -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {% block js %}{% endblock js %}
</body>

<!-- Footer -->
<footer class="page-footer font-small blue footer">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2021 Copyright:
    <a href="http://takkare.com/"> TAKkare Co., Ltd. All right reserved.</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</html>

templates/inventory_report.html
{% extends "base.html" %}
{% block head_title %} | 庫存報表{% endblock %}
{% block extra_head %}
{% load static %}
<meta charset="utf-8">
{% endblock extra_head %}

{% block content %}
<br>
<div class="container">
    <div class="card mb-3">
        <div class="card-body">
            <h3>庫存報表</h3>
            <p>* 輸入日會被轉換為當週週一日期</p>
            <form method="POST" action="" id="regenerate" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-hover">
                    <tbody>
                        <tr style="border-bottom: hidden">
                            <td>
                                <div class="input-group mb-3">
                                    <label class="input-group-text" for="date">日期</label>
                                    <input type="date" class="form-control" id="date" name="date" format="YYYY-MM-DD" placeholder="YYYY-MM-DD" required>
                                    <button class="btn btn-outline-secondary" id="submit_form">重新產生報表</button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
                <table id="reports" class="display" style="width:100%">
                    <thead>
                        <th>日期</th>
                        <th>報告</th>
                    </thead>
                    <tbody>
                        {% for date, filename in reports.items %}
                        <tr>
                            <td>{{ date }}</td>
                            <td><a href={% url 'inventory:download' filename=filename %}>{{ filename }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#reports').DataTable( {
            "scrollY":        "200px",
            "scrollCollapse": true,
            "paging":         false
        } );
    } );
    $('form').submit(function () {
        $('#submit_form').val('處理中 ...')
            .attr('disabled','disabled');
            return;
    });
</script>
{% endblock js %}

templates/members_report.html
{% extends "base.html" %}
{% block head_title %} 會員報表{% endblock %}
{% block extra_head %}
{% load static %}
<meta charset="utf-8">
{% endblock extra_head %}

{% block content %}
<br>
<div class="container">
    <div class="card mb-3">
        <div class="card-body">
            <h3>會員報表</h3>
                <table id="reports" class="display" style="width:100%">
                    <thead>
                        <th>日期</th>
                        <th>報告</th>
                    </thead>
                    <tbody>
                        {% for date, filename in reports.items %}
                        <tr>
                            <td>{{ date }}</td>
                            <td><a href={% url 'members:download' filename=filename %}>{{ filename }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#reports').DataTable( {
            "scrollY":        "200px",
            "scrollCollapse": true,
            "paging":         false
        } );
    } );
</script>
{% endblock js %}

templates/sales_report.html
{% extends "base.html" %}
{% block head_title %} 銷售報表{% endblock %}
{% block extra_head %}
{% load static %}
<meta charset="utf-8">
{% endblock extra_head %}

{% block content %}
<br>
<div class="container">
    <div class="card mb-3">
        <div class="card-body">
            <h3>銷售報表</h3>
                <table id="reports" class="display" style="width:100%">
                    <thead>
                        <th>日期</th>
                        <th>報告</th>
                    </thead>
                    <tbody>
                        {% for date, filename in reports.items %}
                        <tr>
                            <td>{{ date }}</td>
                            <td><a href={% url 'smt_report:download' filename=filename %}>{{ filename }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#reports').DataTable( {
            "scrollY":        "200px",
            "scrollCollapse": true,
            "paging":         false
        } );
    } );
</script>
{% endblock js %}

templates/upload_inventory.html
{% extends "base.html" %}
{% block head_title %} | 庫存資料上傳{% endblock %}
{% block extra_head %}
{% load static %}
<meta charset="utf-8">
{% endblock extra_head %}

{% block content %}
<br>
<div class="container">
    <div class="card mb-3">
        <div class="card-body">
            <h3>庫存資料上傳</h3>
            <form method="POST" action="" id="upload_file" enctype="multipart/form-data">
                {% csrf_token %}
                {% if errors %}
                {% for error in errors %}
                <font color="#FF0000">
                    <p style="font-size: 12px; ">* {{ error }}</p>
                </font>
                {% endfor %}
                {% endif %}
                <table class="table table-hover">
                    <tbody>
                        <tr style="border-bottom: hidden">
                            <td>
                                <div class="input-group mb-3">
                                    <input type="file" class="form-control" id="inventory" name="inventory">
                                    <label class="input-group-text" for="inventory">Upload</label>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <button id="submit_form" style="background-color: #19bdf2; border-color: #19bdf2;" class="btn btn-primary btn-lg btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $('form').submit(function () {
        $('#submit_form').val('處理中 ...')
            .attr('disabled','disabled');
            return;
    });
</script>
{% endblock js %}

templates/upload_smt.html
{% extends "base.html" %}
{% block head_title %} | 銷售資料上傳{% endblock %}
{% block extra_head %}
{% load static %}
<meta charset="utf-8">
{% endblock extra_head %}

{% block content %}
<br>
<div class="container">
    <div class="card mb-3">
        <div class="card-body">
            <h3>銷售資料上傳</h3>
            <form method="POST" action="" id="upload_file" enctype="multipart/form-data">
                {% csrf_token %}
                {% if errors %}
                {% for error in errors %}
                <font color="#FF0000">
                    <p style="font-size: 12px; ">* {{ error }}</p>
                </font>
                {% endfor %}
                {% endif %}
                <table class="table table-hover">
                    <tbody>
                        <tr style="border-bottom: hidden">
                            <td>                                
                                會員日期商品消費明細表上傳                         
                                <div class="input-group mb-3">
                                    <input type="file" class="form-control" id="smt1" name="smt1">
                                    <label class="input-group-text" for="smt1">Upload</label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                訂金查詢作業上傳
                                <div class="input-group mb-3">
                                    <input type="file" class="form-control" id="smt2" name="smt2">
                                    <label class="input-group-text" for="smt2">Upload</label>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                訂金未出貨商品明細表上傳
                                <div class="input-group mb-3">
                                    <input type="file" class="form-control" id="smt3" name="smt3">
                                    <label class="input-group-text" for="smt3">Upload</label>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <button id="submit_form" style="background-color: #19bdf2; border-color: #19bdf2;" class="btn btn-primary btn-lg btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $('form').submit(function () {
        $('#submit_form').val('處理中 ...')
            .attr('disabled','disabled');
            return;
    });
</script>
{% endblock js %}
